/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.text.DecimalFormat;

/**
 *
 * @author DAN
 */
public class DetilERNN extends javax.swing.JFrame {

    
    private int TIMESTEP;
    private int INPUT_NEURON;
    private int HIDDEN_NEURON;
    /**
     * Creates new form DetilERNN
     */
    public DetilERNN() {
        initComponents();     
    }

    /**
     *
     * @param bobotTIH bobotTIH : array 3 Dimensi
     * @param bobotBiasTIH bobotBiasTIH : array 2 Dimensi
     * @param bobotTCH bobotTCH : array 3 Dimensi
     * @param bobotHO bobotHO : array 2 Dimensi
     * @param bobotBiasHO bobotBiasHO : array 1 Dimensi
     */
    public DetilERNN(double[][][] bobotTIH, double[][] bobotBiasTIH,double[][][] bobotTCH, 
            double[][] bobotHO, double[] bobotBiasHO) {
        initComponents();  
        tampilBobotIH(bobotTIH, bobotBiasTIH);
        tampilBobotCH(bobotTCH);
        DecimalFormat formatEmpat = new DecimalFormat("#.######");
        tampilBobotHO(bobotHO, bobotBiasHO, formatEmpat);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    private void tampilBobotIH(double[][][] bobotTIH, double[][] bobotBiasTIH){
        DecimalFormat formatEmpat = new DecimalFormat("#.######");
        
        txtAreaBobotHasilPelatihan.append("bobot INPUT-HIDDEN pada setiap TIMESTEP \n");
        for (int t = 0; t < bobotTIH.length; t++) {
            txtAreaBobotHasilPelatihan.append("TIMESTEP KE-"+t+"\n");
            for (int i = 0; i < bobotTIH[0].length; i++) {
                for (int h = 0; h < bobotTIH[0][0].length; h++) {
                    txtAreaBobotHasilPelatihan.append(formatEmpat.format(bobotTIH[t][i][h])+"\t");
                }
                txtAreaBobotHasilPelatihan.append("\n");
            }
            txtAreaBobotHasilPelatihan.append("bobot BIAS INPUT-HIDDEN pada TIMESTEP "+t+"\n");
            for (int h = 0; h < bobotBiasTIH[0].length; h++) {                
                txtAreaBobotHasilPelatihan.append(formatEmpat.format(bobotBiasTIH[t][h])+"\t");
            }
            txtAreaBobotHasilPelatihan.append("\n\n");
        }
    }
    
    private void tampilBobotCH(double[][][] bobotTCH){
        DecimalFormat formatDuaPuluh = new DecimalFormat("#.####################");
        txtAreaBobotHasilPelatihan2.append("bobot CONTEXT-HIDDEN pada setiap TIMESTEP \n");
        for (int t = 0; t < bobotTCH.length; t++) {
            txtAreaBobotHasilPelatihan2.append("TIMESTEP KE-"+t+"\n");
            for (int c = 0; c < bobotTCH[0].length; c++) {
                for (int h = 0; h < bobotTCH[0][0].length; h++) {
                    txtAreaBobotHasilPelatihan2.append(formatDuaPuluh.format(bobotTCH[t][c][h])+"\t");
                }
                txtAreaBobotHasilPelatihan2.append("\n");
            }
            txtAreaBobotHasilPelatihan2.append("\n");
        }
    }
    
    private void tampilBobotHO(double[][] bobotHO,double[] bobotBiasHO,DecimalFormat formatDesimal){        
        txtAreaBobotHasilPelatihan3.append("bobot HIDDEN-OUTPUT \n");
        for (int h = 0; h < bobotHO.length; h++) {
            for (int o = 0; o < bobotHO[0].length; o++) {
                txtAreaBobotHasilPelatihan3.append(formatDesimal.format(bobotHO[h][o])+"\t");
            }
            txtAreaBobotHasilPelatihan3.append("\n");            
        }
        txtAreaBobotHasilPelatihan3.append("bobot BIAS HIDDEN-OUTPUT \n");
        for (int o = 0; o < bobotBiasHO.length; o++) {
            txtAreaBobotHasilPelatihan3.append(formatDesimal.format(bobotBiasHO[o])+"\t");
        }
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBobotHasilPelatihan = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaBobotHasilPelatihan2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaBobotHasilPelatihan3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("ERNN Weight Detail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(299, 299, 299))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Input-Hidden (and the Bias)"));

        txtAreaBobotHasilPelatihan.setColumns(20);
        txtAreaBobotHasilPelatihan.setRows(5);
        txtAreaBobotHasilPelatihan.setToolTipText("");
        txtAreaBobotHasilPelatihan.setBorder(null);
        jScrollPane1.setViewportView(txtAreaBobotHasilPelatihan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Context-Hidden"));

        txtAreaBobotHasilPelatihan2.setColumns(20);
        txtAreaBobotHasilPelatihan2.setRows(5);
        jScrollPane2.setViewportView(txtAreaBobotHasilPelatihan2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hidden->Output"));

        txtAreaBobotHasilPelatihan3.setColumns(20);
        txtAreaBobotHasilPelatihan3.setRows(5);
        jScrollPane3.setViewportView(txtAreaBobotHasilPelatihan3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetilERNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetilERNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetilERNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetilERNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetilERNN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAreaBobotHasilPelatihan;
    private javax.swing.JTextArea txtAreaBobotHasilPelatihan2;
    private javax.swing.JTextArea txtAreaBobotHasilPelatihan3;
    // End of variables declaration//GEN-END:variables
}
