/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author DAN
 */
public class DetilMFCC extends javax.swing.JFrame {

    /**
     * Creates new form DetilMFCC
     */
    public DetilMFCC() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLokasiFileAudio = new javax.swing.JTextField();
        btnAnalisis = new javax.swing.JButton();
        btnBrowseFile = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        grupPreProcessing = new javax.swing.JPanel();
        tabPanePreProcessing = new javax.swing.JTabbedPane();
        panelSinyalAsli = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSinyalAsli = new javax.swing.JTextArea();
        panelSilenceRemoval = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaSilenceRemoval = new javax.swing.JTextArea();
        panelDCRemoval = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDCRemoval = new javax.swing.JTextArea();
        panelPreEmphasis = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaPreEmp = new javax.swing.JTextArea();
        panelFrameBlocking = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaFrameBlocking = new javax.swing.JTextArea();
        panelTimeAlignment = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAreaTimeAlignment = new javax.swing.JTextArea();
        panelWindowing = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAreaWindowing = new javax.swing.JTextArea();
        grupEkstraksiCiri = new javax.swing.JPanel();
        tabPaneMFCC = new javax.swing.JTabbedPane();
        panelFFT = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtAreaFFT = new javax.swing.JTextArea();
        panelMelFreq = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtAreaMelFreq = new javax.swing.JTextArea();
        panelDCT = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtAreaDCT = new javax.swing.JTextArea();
        panelNormalisasi = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtAreaNormalisasi = new javax.swing.JTextArea();
        panelThresholding = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtAreaThresholding = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detil Ekstraksi Ciri");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Pilih File Audio (16Khz)");

        btnAnalisis.setText("Analisis MFCC");

        btnBrowseFile.setText("Browse File");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txtLokasiFileAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrowseFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnalisis)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLokasiFileAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalisis)
                    .addComponent(btnBrowseFile))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        grupPreProcessing.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "PreProcessing"));

        txtAreaSinyalAsli.setColumns(20);
        txtAreaSinyalAsli.setRows(5);
        jScrollPane1.setViewportView(txtAreaSinyalAsli);

        javax.swing.GroupLayout panelSinyalAsliLayout = new javax.swing.GroupLayout(panelSinyalAsli);
        panelSinyalAsli.setLayout(panelSinyalAsliLayout);
        panelSinyalAsliLayout.setHorizontalGroup(
            panelSinyalAsliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        panelSinyalAsliLayout.setVerticalGroup(
            panelSinyalAsliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        tabPanePreProcessing.addTab("Sinyal Asli", panelSinyalAsli);

        txtAreaSilenceRemoval.setColumns(20);
        txtAreaSilenceRemoval.setRows(5);
        jScrollPane2.setViewportView(txtAreaSilenceRemoval);

        javax.swing.GroupLayout panelSilenceRemovalLayout = new javax.swing.GroupLayout(panelSilenceRemoval);
        panelSilenceRemoval.setLayout(panelSilenceRemovalLayout);
        panelSilenceRemovalLayout.setHorizontalGroup(
            panelSilenceRemovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        panelSilenceRemovalLayout.setVerticalGroup(
            panelSilenceRemovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        tabPanePreProcessing.addTab("Hasil Silence Rmoval", panelSilenceRemoval);

        txtAreaDCRemoval.setColumns(20);
        txtAreaDCRemoval.setRows(5);
        jScrollPane3.setViewportView(txtAreaDCRemoval);

        javax.swing.GroupLayout panelDCRemovalLayout = new javax.swing.GroupLayout(panelDCRemoval);
        panelDCRemoval.setLayout(panelDCRemovalLayout);
        panelDCRemovalLayout.setHorizontalGroup(
            panelDCRemovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        panelDCRemovalLayout.setVerticalGroup(
            panelDCRemovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        tabPanePreProcessing.addTab("DC Removal", panelDCRemoval);

        txtAreaPreEmp.setColumns(20);
        txtAreaPreEmp.setRows(5);
        jScrollPane4.setViewportView(txtAreaPreEmp);

        javax.swing.GroupLayout panelPreEmphasisLayout = new javax.swing.GroupLayout(panelPreEmphasis);
        panelPreEmphasis.setLayout(panelPreEmphasisLayout);
        panelPreEmphasisLayout.setHorizontalGroup(
            panelPreEmphasisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        panelPreEmphasisLayout.setVerticalGroup(
            panelPreEmphasisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        tabPanePreProcessing.addTab("Pre Emphasis", panelPreEmphasis);

        txtAreaFrameBlocking.setColumns(20);
        txtAreaFrameBlocking.setRows(5);
        jScrollPane5.setViewportView(txtAreaFrameBlocking);

        javax.swing.GroupLayout panelFrameBlockingLayout = new javax.swing.GroupLayout(panelFrameBlocking);
        panelFrameBlocking.setLayout(panelFrameBlockingLayout);
        panelFrameBlockingLayout.setHorizontalGroup(
            panelFrameBlockingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        panelFrameBlockingLayout.setVerticalGroup(
            panelFrameBlockingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        tabPanePreProcessing.addTab("Frame Blocking", panelFrameBlocking);

        txtAreaTimeAlignment.setColumns(20);
        txtAreaTimeAlignment.setRows(5);
        jScrollPane6.setViewportView(txtAreaTimeAlignment);

        javax.swing.GroupLayout panelTimeAlignmentLayout = new javax.swing.GroupLayout(panelTimeAlignment);
        panelTimeAlignment.setLayout(panelTimeAlignmentLayout);
        panelTimeAlignmentLayout.setHorizontalGroup(
            panelTimeAlignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        panelTimeAlignmentLayout.setVerticalGroup(
            panelTimeAlignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        tabPanePreProcessing.addTab("Time Alignment", panelTimeAlignment);

        txtAreaWindowing.setColumns(20);
        txtAreaWindowing.setRows(5);
        jScrollPane7.setViewportView(txtAreaWindowing);

        javax.swing.GroupLayout panelWindowingLayout = new javax.swing.GroupLayout(panelWindowing);
        panelWindowing.setLayout(panelWindowingLayout);
        panelWindowingLayout.setHorizontalGroup(
            panelWindowingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        panelWindowingLayout.setVerticalGroup(
            panelWindowingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        tabPanePreProcessing.addTab("Windowing", panelWindowing);

        javax.swing.GroupLayout grupPreProcessingLayout = new javax.swing.GroupLayout(grupPreProcessing);
        grupPreProcessing.setLayout(grupPreProcessingLayout);
        grupPreProcessingLayout.setHorizontalGroup(
            grupPreProcessingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanePreProcessing)
        );
        grupPreProcessingLayout.setVerticalGroup(
            grupPreProcessingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupPreProcessingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabPanePreProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        grupEkstraksiCiri.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ekstraksi Ciri"));

        txtAreaFFT.setColumns(20);
        txtAreaFFT.setRows(5);
        jScrollPane9.setViewportView(txtAreaFFT);

        javax.swing.GroupLayout panelFFTLayout = new javax.swing.GroupLayout(panelFFT);
        panelFFT.setLayout(panelFFTLayout);
        panelFFTLayout.setHorizontalGroup(
            panelFFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        panelFFTLayout.setVerticalGroup(
            panelFFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        tabPaneMFCC.addTab("FFT", panelFFT);

        txtAreaMelFreq.setColumns(20);
        txtAreaMelFreq.setRows(5);
        jScrollPane10.setViewportView(txtAreaMelFreq);

        javax.swing.GroupLayout panelMelFreqLayout = new javax.swing.GroupLayout(panelMelFreq);
        panelMelFreq.setLayout(panelMelFreqLayout);
        panelMelFreqLayout.setHorizontalGroup(
            panelMelFreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        panelMelFreqLayout.setVerticalGroup(
            panelMelFreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        tabPaneMFCC.addTab("Mel Frequency Warping", panelMelFreq);

        txtAreaDCT.setColumns(20);
        txtAreaDCT.setRows(5);
        jScrollPane11.setViewportView(txtAreaDCT);

        javax.swing.GroupLayout panelDCTLayout = new javax.swing.GroupLayout(panelDCT);
        panelDCT.setLayout(panelDCTLayout);
        panelDCTLayout.setHorizontalGroup(
            panelDCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        panelDCTLayout.setVerticalGroup(
            panelDCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        tabPaneMFCC.addTab("DCT", panelDCT);

        txtAreaNormalisasi.setColumns(20);
        txtAreaNormalisasi.setRows(5);
        jScrollPane12.setViewportView(txtAreaNormalisasi);

        javax.swing.GroupLayout panelNormalisasiLayout = new javax.swing.GroupLayout(panelNormalisasi);
        panelNormalisasi.setLayout(panelNormalisasiLayout);
        panelNormalisasiLayout.setHorizontalGroup(
            panelNormalisasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        panelNormalisasiLayout.setVerticalGroup(
            panelNormalisasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        tabPaneMFCC.addTab("Normalisasi", panelNormalisasi);

        txtAreaThresholding.setColumns(20);
        txtAreaThresholding.setRows(5);
        jScrollPane8.setViewportView(txtAreaThresholding);

        javax.swing.GroupLayout panelThresholdingLayout = new javax.swing.GroupLayout(panelThresholding);
        panelThresholding.setLayout(panelThresholdingLayout);
        panelThresholdingLayout.setHorizontalGroup(
            panelThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        panelThresholdingLayout.setVerticalGroup(
            panelThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        tabPaneMFCC.addTab("Thresholding", panelThresholding);

        javax.swing.GroupLayout grupEkstraksiCiriLayout = new javax.swing.GroupLayout(grupEkstraksiCiri);
        grupEkstraksiCiri.setLayout(grupEkstraksiCiriLayout);
        grupEkstraksiCiriLayout.setHorizontalGroup(
            grupEkstraksiCiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupEkstraksiCiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneMFCC))
        );
        grupEkstraksiCiriLayout.setVerticalGroup(
            grupEkstraksiCiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupEkstraksiCiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneMFCC))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(grupPreProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grupEkstraksiCiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(grupPreProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grupEkstraksiCiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetilMFCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetilMFCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetilMFCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetilMFCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetilMFCC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisis;
    private javax.swing.JButton btnBrowseFile;
    private javax.swing.JPanel grupEkstraksiCiri;
    private javax.swing.JPanel grupPreProcessing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel panelDCRemoval;
    private javax.swing.JPanel panelDCT;
    private javax.swing.JPanel panelFFT;
    private javax.swing.JPanel panelFrameBlocking;
    private javax.swing.JPanel panelMelFreq;
    private javax.swing.JPanel panelNormalisasi;
    private javax.swing.JPanel panelPreEmphasis;
    private javax.swing.JPanel panelSilenceRemoval;
    private javax.swing.JPanel panelSinyalAsli;
    private javax.swing.JPanel panelThresholding;
    private javax.swing.JPanel panelTimeAlignment;
    private javax.swing.JPanel panelWindowing;
    private javax.swing.JTabbedPane tabPaneMFCC;
    private javax.swing.JTabbedPane tabPanePreProcessing;
    private javax.swing.JTextArea txtAreaDCRemoval;
    private javax.swing.JTextArea txtAreaDCT;
    private javax.swing.JTextArea txtAreaFFT;
    private javax.swing.JTextArea txtAreaFrameBlocking;
    private javax.swing.JTextArea txtAreaMelFreq;
    private javax.swing.JTextArea txtAreaNormalisasi;
    private javax.swing.JTextArea txtAreaPreEmp;
    private javax.swing.JTextArea txtAreaSilenceRemoval;
    private javax.swing.JTextArea txtAreaSinyalAsli;
    private javax.swing.JTextArea txtAreaThresholding;
    private javax.swing.JTextArea txtAreaTimeAlignment;
    private javax.swing.JTextArea txtAreaWindowing;
    private javax.swing.JTextField txtLokasiFileAudio;
    // End of variables declaration//GEN-END:variables
}
