/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import CSVIO.CSVReader;
import NeuralNetwork.ElmanSRN;
import java.text.DecimalFormat;
import javax.xml.soap.Detail;

/**
 *
 * @author DAN
 */
public class HalamanERNN extends javax.swing.JFrame {
    int TIMESTEP, JUMLAH_FITUR_MFCC;
    int OUTPUT_NEURON = 10;
    
    double[][][] bobotTIH;
    double[][][] bobotTCH;
    double[][] bobotBiasTIH;
    double[][] bobotHO;
    double[] bobotBiasHO;
    
    /**
     * Creates new form HalamanERNN
     */
    public HalamanERNN() {
        initComponents();
    }

    public double[][][] getBobotTIH() {
        return bobotTIH;
    }

    public double[][] getBobotBiasTIH() {
        return bobotBiasTIH;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnDetilERNN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLokasiFileTraining = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLokasiFileTesting = new javax.swing.JTextField();
        btnMulai = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTimestep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFiturInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEpoch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLearningRate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHiddenNeuron = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaBobotHasilPelatihan3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Classification With ERNN");

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnDetilERNN.setText("Lihat Detil ERNN");
        btnDetilERNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetilERNNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185)
                .addComponent(btnDetilERNN)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetilERNN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Insert the location of csv file contain training dataset");

        txtLokasiFileTraining.setText("C:\\Users\\DAN\\Downloads\\Video\\b.csv");

        jLabel3.setText("Insert the location of csv file contain test dataset");

        btnMulai.setText("Mulai");
        btnMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiActionPerformed(evt);
            }
        });

        jLabel4.setText("Timestep on the dataset");

        txtTimestep.setText("7");

        jLabel5.setText("Number of features in each timestep");

        txtFiturInput.setText("12");
        txtFiturInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiturInputActionPerformed(evt);
            }
        });

        jLabel6.setText("Number of Epoch");

        txtEpoch.setText("1000");

        jLabel7.setText("Learning Rate");

        txtLearningRate.setText("0.05");

        jLabel8.setText("No. of Hidden Neuron");

        txtHiddenNeuron.setText("15");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLokasiFileTraining, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txtLokasiFileTesting))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLearningRate)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEpoch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTimestep)
                                        .addComponent(txtFiturInput, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                    .addComponent(txtHiddenNeuron, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLokasiFileTraining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLokasiFileTesting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTimestep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFiturInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtEpoch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtHiddenNeuron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnMulai)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel10.setText("0.00 %");

        jLabel9.setText("Akurasi terhadap data training");

        jLabel11.setText("Data Latih Berhasil =");

        jLabel12.setText("100/100");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 150));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("Akurasi terhadap data testing");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel14.setText("0.00 %");

        jLabel15.setText("Data Testing Berhasil Dikenali =");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel14))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel15)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 290, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAreaBobotHasilPelatihan3.setColumns(20);
        txtAreaBobotHasilPelatihan3.setRows(5);
        jScrollPane3.setViewportView(txtAreaBobotHasilPelatihan3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HalamanUtama hUtama = new HalamanUtama();
        hUtama.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiActionPerformed
        // TODO add your handling code here:
        //untuk tiga dimensi maka
        int barisIndex, barisIndexTes;
        int INPUT_NEURON, HIDDEN_NEURON;
        int EPOCH;
        double LEARNING_RATE;
        
        String lokasiDataTraining = "";
        String lokasiDataTesting = "";
        CSVReader csr = new CSVReader();
        
        //input lokasi dataTraining dan dataTesting (dalam bentuk file CSV)
        lokasiDataTraining = txtLokasiFileTraining.getText();
        lokasiDataTesting = txtLokasiFileTesting.getText();
        
        /*
        * Dapatkan parameter yang dibutuhkan oleh ERNN seperti : 
        * TIMESTEP pada data
        * jumlah INPUT NEURON pada Setiap TIMESTEP
        */
        TIMESTEP = Integer.valueOf(txtTimestep.getText());
        INPUT_NEURON = Integer.valueOf(txtFiturInput.getText());
        EPOCH = Integer.valueOf(txtEpoch.getText());
        LEARNING_RATE = Double.valueOf(txtLearningRate.getText());
        HIDDEN_NEURON = Integer.valueOf(txtHiddenNeuron.getText());
        int banyakKolom = TIMESTEP * INPUT_NEURON;
        
        //lakukan penghitungan terhadap jumlah dataset
        barisIndex = csr.hitungJumlahDataTraining(lokasiDataTraining);
        barisIndexTes = csr.hitungJumlahDataTraining(lokasiDataTesting);
        
        //sediakan array untuk menampung hasil dari pembacaan file csv
        /*
        @dataTraining2Dimensi = array 2D untuk menampung hasil pembacaan, 
        nantinya akan dirubah kedalam bentuk 3D [UrutanDataSample][TIMESTEP][INPUT_NEURON]
        
        @dataTarget = data target dari setiap sample input yang ada (data target dalam tiap baris)
        */
        double[][] dataTraining2Dimensi = new double[barisIndex][banyakKolom];
        double[][] dataTarget = new double[barisIndex][OUTPUT_NEURON];
        double[][] dataTes2Dimensi = new double[barisIndex][OUTPUT_NEURON];
        
        //baca dataset yang ada dalam file CSV
        dataTraining2Dimensi = csr.bacaDataTraining(lokasiDataTraining, barisIndex, banyakKolom);
        dataTes2Dimensi = csr.bacaDataTraining(lokasiDataTesting, barisIndex, banyakKolom);

        //kemudian rubah data 2 Dimensi tersebut kedalam data 3 Dimensi (dataInput bukan target)
        double[][][] dataTraining = new double[barisIndex][TIMESTEP][INPUT_NEURON];
        double[][][] dataTes = new double[barisIndexTes][TIMESTEP][INPUT_NEURON];

        int pointer;
        for (int i = 0; i < barisIndex; i++) {
            pointer = 0;
            for (int j = 0; j < TIMESTEP; j++) {
                for (int k = 0; k < INPUT_NEURON; k++) {
                    dataTraining[i][j][k] = dataTraining2Dimensi[i][pointer];
                    pointer++;
                }
            }            
        }     
        
        for (int i = 0; i < barisIndexTes; i++) {
            pointer = 0;
            for (int j = 0; j < TIMESTEP; j++) {
                for (int k = 0; k < INPUT_NEURON; k++) {
                    dataTes[i][j][k] = dataTes2Dimensi[i][pointer];
                    pointer++;
                }
            }
        }
        
        //setelah data 3 Dimensi didapatkan, selanjutnya tinggal menentukan data target dari pelatihan
        dataTarget = csr.bacaDataTarget(lokasiDataTraining, barisIndex, OUTPUT_NEURON, banyakKolom); //buat array output yang diharapkan untuk setiap sample data                       
        
//        ElmanSRN ernn = new ElmanSRN(5, 0.05, 10000, 6);
        ElmanSRN ernn = new ElmanSRN(HIDDEN_NEURON, TIMESTEP, LEARNING_RATE, EPOCH, barisIndex, dataTraining, dataTarget, dataTes);
        ernn.main();
        System.out.println(barisIndexTes);
        
//        double[][][] bobotTIH;
//        double[][][] bobotTCH;
//        double[][] bobotBiasTIH;
//        double[][] bobotHO;
//        double[] bobotBiasHO;
        
        bobotTIH = ernn.getBobotTIH();
        bobotTCH = ernn.getBobotTCH();
        bobotBiasTIH = ernn.getBobotBiasTIH();
        bobotHO = ernn.getBobotHO();
        bobotBiasHO = ernn.getBobotBiasHO();
        
        DecimalFormat formatEmpat = new DecimalFormat("#.######");
        
        //INPUT -> HIDDEN
    /*
        txtAreaBobotHasilPelatihan.append("bobot INPUT-HIDDEN pada setiap TIMESTEP \n");
        for (int t = 0; t < bobotTIH.length; t++) {
            txtAreaBobotHasilPelatihan.append("TIMESTEP KE-"+t+"\n");
            for (int i = 0; i < bobotTIH[0].length; i++) {
                for (int h = 0; h < bobotTIH[0][0].length; h++) {
                    txtAreaBobotHasilPelatihan.append(formatEmpat.format(bobotTIH[t][i][h])+"\t");
                }
                txtAreaBobotHasilPelatihan.append("\n");
            }
            txtAreaBobotHasilPelatihan.append("bobot BIAS INPUT-HIDDEN pada TIMESTEP "+t+"\n");
            for (int h = 0; h < bobotBiasTIH[0].length; h++) {                
                txtAreaBobotHasilPelatihan.append(formatEmpat.format(bobotBiasTIH[t][h])+"\t");
            }
            txtAreaBobotHasilPelatihan.append("\n\n");
        }
      */  
        //HIDDEN -> HIDDEN (CONTEXT)
        /*
        DecimalFormat formatDuaPuluh = new DecimalFormat("#.####################");
        txtAreaBobotHasilPelatihan2.append("bobot CONTEXT-HIDDEN pada setiap TIMESTEP \n");
        for (int t = 0; t < bobotTCH.length; t++) {
            txtAreaBobotHasilPelatihan2.append("TIMESTEP KE-"+t+"\n");
            for (int c = 0; c < bobotTCH[0].length; c++) {
                for (int h = 0; h < bobotTCH[0][0].length; h++) {
                    txtAreaBobotHasilPelatihan2.append(formatDuaPuluh.format(bobotTCH[t][c][h])+"\t");
                }
                txtAreaBobotHasilPelatihan2.append("\n");
            }
            txtAreaBobotHasilPelatihan2.append("\n");
        }
        */
        //HIDDEN -> OUTPUT
//        txtAreaBobotHasilPelatihan3.append("bobot HIDDEN-OUTPUT \n");
//        for (int h = 0; h < bobotHO.length; h++) {
//            for (int o = 0; o < bobotHO[0].length; o++) {
//                txtAreaBobotHasilPelatihan3.append(formatEmpat.format(bobotHO[h][o])+"\t");
//            }
//            txtAreaBobotHasilPelatihan3.append("\n");            
//        }
//        txtAreaBobotHasilPelatihan3.append("bobot BIAS HIDDEN-OUTPUT \n");
//        for (int o = 0; o < bobotBiasHO.length; o++) {
//            txtAreaBobotHasilPelatihan3.append(formatEmpat.format(bobotBiasHO[o])+"\t");
//        }
    }//GEN-LAST:event_btnMulaiActionPerformed

     public void tampilkanArray(double[][][] arrayTes){
        for (int i = 0; i < arrayTes.length; i++) {
            System.out.println(i);
            for (int j = 0; j < arrayTes[0].length; j++) {
                for (int k = 0; k < arrayTes[0][0].length; k++) {
                    System.out.print(arrayTes[i][j][k]+"\t");
                }                
                System.out.println("");
            }
        }
    }
     
    public void tampilkanArray(double[][] arrayTes){
        for (int j = 0; j < arrayTes.length; j++) {
            System.out.print(j+" \t= ");
            for (int k = 0; k < arrayTes[0].length; k++) {
                System.out.print(arrayTes[j][k]+"\t");
            }                
            System.out.println("");
        }
        System.out.println(arrayTes.length+","+arrayTes[0].length);
    }
    
    private void txtFiturInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiturInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiturInputActionPerformed

    private void btnDetilERNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetilERNNActionPerformed
        // TODO add your handling code here:
        int HIDDEN_NEURON = Integer.valueOf(txtHiddenNeuron.getText());
        int TIMESTEP = Integer.valueOf(txtTimestep.getText());
        DetilERNN detil = new DetilERNN(bobotTIH,bobotBiasTIH,bobotTCH,bobotHO,bobotBiasHO);                
        detil.setVisible(true);
    }//GEN-LAST:event_btnDetilERNNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanERNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanERNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanERNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanERNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanERNN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetilERNN;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMulai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAreaBobotHasilPelatihan3;
    private javax.swing.JTextField txtEpoch;
    private javax.swing.JTextField txtFiturInput;
    private javax.swing.JTextField txtHiddenNeuron;
    private javax.swing.JTextField txtLearningRate;
    private javax.swing.JTextField txtLokasiFileTesting;
    private javax.swing.JTextField txtLokasiFileTraining;
    private javax.swing.JTextField txtTimestep;
    // End of variables declaration//GEN-END:variables
}
