/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ArrayManipulator.ArrayManipulator;
import CSVIO.CSVReader;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author DAN
 */
public class LoadBobot extends javax.swing.JFrame {
    HalamanERNN hERNN;

    /**
     * Creates new form LoadBobot
     */
    public LoadBobot(HalamanERNN halaman) {
        initComponents();
        hERNN = halaman;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLokasiFile = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTIMESTEP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtINPUT_NEURON = new javax.swing.JTextField();
        txtHIDDEN_NEURON = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOUTPUT_NEURON = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Folder Location");

        jButton1.setText("Browse..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Use The Weight for ERNN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("TIMESTEP");

        txtTIMESTEP.setText("5");

        jLabel3.setText("INPUT_NEURON");

        jLabel4.setText("HIDDEN_NEURON");

        txtINPUT_NEURON.setText("12");

        txtHIDDEN_NEURON.setText("15");

        jLabel5.setText("OUTPUT_NEURON");

        txtOUTPUT_NEURON.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOUTPUT_NEURON)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtHIDDEN_NEURON, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtINPUT_NEURON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(txtTIMESTEP, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(txtLokasiFile, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLokasiFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTIMESTEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtINPUT_NEURON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHIDDEN_NEURON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOUTPUT_NEURON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double[][] bobotTIHTemp; //nanti akan dikonversi menjadi 3D
        double[][] bobotTCHTemp; //nanti akan dikonversi menjadi 3D

        double[][][] bobotTIH;
        double[][][] bobotTCH;
        double[][] bobotBiasTIH;
        double[][] bobotHO;
        double[] bobotBiasHO;

        int TIMESTEP;// = 5;
        int INPUT_NEURON;// = 12;
        int HIDDEN_NEURON;// = 15;
        int OUTPUT_NEURON;// = 10;
        
        TIMESTEP = Integer.valueOf(txtTIMESTEP.getText());
        INPUT_NEURON = Integer.valueOf(txtINPUT_NEURON.getText());
        HIDDEN_NEURON = Integer.valueOf(txtHIDDEN_NEURON.getText());
        OUTPUT_NEURON = Integer.valueOf(txtOUTPUT_NEURON.getText());
        
        //choose the folder
        //String folder = "C:\\Users\\DAN\\Documents\\BobotOutput\\";
        String folder = txtLokasiFile.getText();
        
        //Read the weight from .csv File
        String lokasiBobotTIH = folder+"\\bobotTIH.csv";
        String lokasiBobotBiasTIH = folder+"\\bobotBiasTIH.csv";
        String lokasiBobotTCH = folder+"\\bobotTCH.csv";
        String lokasiBobotHO = folder+"\\bobotHO.csv";
        String lokasiBobotBiasHO = folder+"\\bobotBiasHO.csv";
        
        CSVReader csvr = new CSVReader();
        
        bobotTIHTemp = csvr.bacaArray2D(lokasiBobotTIH, TIMESTEP*INPUT_NEURON, HIDDEN_NEURON);
        bobotTCHTemp = csvr.bacaArray2D(lokasiBobotTCH, TIMESTEP*HIDDEN_NEURON, HIDDEN_NEURON);
        bobotBiasTIH = csvr.bacaArray2D(lokasiBobotBiasTIH, TIMESTEP, HIDDEN_NEURON);
        bobotBiasHO = csvr.bacaArray1D(lokasiBobotBiasHO, OUTPUT_NEURON);
        bobotHO = csvr.bacaArray2D(lokasiBobotHO, HIDDEN_NEURON, OUTPUT_NEURON);
        
        //convert 2d array into 3d array
        ArrayManipulator am = new ArrayManipulator();
        bobotTIH = am.array2Dto3D(bobotTIHTemp, TIMESTEP, INPUT_NEURON, HIDDEN_NEURON);
        bobotTCH = am.array2Dto3D(bobotTCHTemp, TIMESTEP, HIDDEN_NEURON, HIDDEN_NEURON);
        
        //then, load the retrieved weight to the HalamanERNN class
        hERNN.bobotTIH = bobotTIH;
        hERNN.bobotBiasTIH = bobotBiasTIH;
        hERNN.bobotTCH = bobotTCH;
        hERNN.bobotHO = bobotHO;
        hERNN.bobotBiasHO = bobotBiasHO;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.showOpenDialog(null);
        
        String filename = String.valueOf(jFileChooser1.getCurrentDirectory());

        txtLokasiFile.setText(filename);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LoadBobot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtHIDDEN_NEURON;
    private javax.swing.JTextField txtINPUT_NEURON;
    private javax.swing.JTextField txtLokasiFile;
    private javax.swing.JTextField txtOUTPUT_NEURON;
    private javax.swing.JTextField txtTIMESTEP;
    // End of variables declaration//GEN-END:variables
}
